---
# Upgrade infra services
# version change:
#   ---------------------------------------
#   infra stack         |   old |   new   |
#   ---------------------------------------
#   healthcheck         |   0   |   2     |
#   network-services    |   6   |   9     |
#   scheduler           |   0   |   3     |
#   ---------------------------------------
# notice:
#   * before upgrading network-services, just make sure scheduler has been stopped.
#

- name: Upgrade healthcheck in env {{rancher_env.id}}
  rancher_stack:
    rancher_parameters: "{{rancher_parameters}}"
    stack_name: healthcheck
    env_id: "{{rancher_env.id}}"
    docker_compose: "{{catalog_infra_dir}}/healthcheck/{{version}}/docker-compose.yml"
    rancher_compose: "{{catalog_infra_dir}}/healthcheck/{{version}}/rancher-compose.yml"
    external_id: "catalog://library:infra*healthcheck:{{version}}"
    action: upgrade
  register: upgrade_healthcheck_stack
  until: upgrade_healthcheck_stack.meta.upgraded
  retries: 5
  delay: 10
  vars:
    version: 2

- name: Finish upgrade healthcheck in env {{rancher_env.id}}
  rancher_stack:
    rancher_parameters: "{{rancher_parameters}}"
    stack_name: healthcheck
    env_id: "{{rancher_env.id}}"
    action: finish_upgrade
  when: upgrade_healthcheck_stack.meta.upgraded
  retries: 5
  delay: 10

- name: Upgrade scheduler in env {{rancher_env.id}}
  rancher_stack:
    rancher_parameters: "{{rancher_parameters}}"
    stack_name: scheduler
    env_id: "{{rancher_env.id}}"
    docker_compose: "{{catalog_infra_dir}}/scheduler/{{version}}/docker-compose.yml"
    rancher_compose: "{{catalog_infra_dir}}/scheduler/{{version}}/rancher-compose.yml"
    external_id: "catalog://library:infra*scheduler:{{version}}"
    action: upgrade
  register: upgrade_scheduler_stack
  until: upgrade_scheduler_stack.meta.upgraded
  retries: 5
  delay: 10
  vars:
    version: 3

- name: Finish upgrade scheduler in env {{rancher_env.id}}
  rancher_stack:
    rancher_parameters: "{{rancher_parameters}}"
    stack_name: scheduler
    env_id: "{{rancher_env.id}}"
    action: finish_upgrade
  when: upgrade_scheduler_stack.meta.upgraded
  retries: 5
  delay: 10

- name: Deactive scheduler in env {{rancher_env.id}}
  rancher_stack:
    rancher_parameters: "{{rancher_parameters}}"
    stack_name: scheduler
    env_id: "{{rancher_env.id}}"
    action: deactivateservices
  register: deactive_scheduler_stack
  until: deactive_scheduler_stack.meta.stopped
  retries: 5
  delay: 10

- name: Upgrade network services in env {{rancher_env.id}}
  rancher_stack:
    rancher_parameters: "{{rancher_parameters}}"
    stack_name: network-services
    env_id: "{{rancher_env.id}}"
    docker_compose: "{{catalog_infra_dir}}/network-services/{{version}}/docker-compose.yml"
    rancher_compose: "{{catalog_infra_dir}}/network-services/{{version}}/rancher-compose.yml"
    external_id: "catalog://library:infra*network-services:{{version}}"
    action: upgrade
  register: upgrade_nw_stack
  until: upgrade_nw_stack.meta.upgraded
  retries: 5
  delay: 10
  vars:
    version: 9

- name: Finish network services in env {{rancher_env.id}}
  rancher_stack:
    rancher_parameters: "{{rancher_parameters}}"
    stack_name: network-services
    env_id: "{{rancher_env.id}}"
    action: finish_upgrade
  when: upgrade_nw_stack.meta.upgraded
  retries: 5
  delay: 10

- name: Active scheduler in env {{rancher_env.id}}
  rancher_stack:
    rancher_parameters: "{{rancher_parameters}}"
    stack_name: scheduler
    env_id: "{{rancher_env.id}}"
    action: activateservices

