---
# Upgrade infra services
# version change:
#   ---------------------------------------
#   infra stack         |   old |   new   |
#   ---------------------------------------
#   beancounter-agent   |   1   |   2     |
#   healthcheck         |   0   |   1     |
#   network-services    |   6   |   7     |
#   scheduler           |   0   |   2     |
#   ---------------------------------------
# notice:
#   * before upgrading network-services, just make sure scheduler has been stopped.
#

- name: Upgrade beancounter agent
  rancher_stack:
    rancher_parameters: "{{rancher_parameters}}"
    stack_name: beancounter-agent
    env_id: "{{rancher_env.id}}"
    docker_compose: "{{catalog_infra_dir}}/beancounter-agent/2/docker-compose.yml"
    rancher_compose: "{{catalog_infra_dir}}/beancounter-agent/2/rancher-compose.yml"
    external_id: "catalog://library:infra*beancounter-agent:2"
    environment:
      INFLUXDB_HOST: "{{influxdb_host}}"
    action: upgrade
  register: upgrade_bc_stack
  until: upgrade_bc_stack.has_key("meta") and upgrade_bc_stack.meta.upgraded
  retries: 5
  delay: 2

- name: Finish upgrade beancounter agent
  rancher_stack:
    rancher_parameters: "{{rancher_parameters}}"
    stack_name: beancounter-agent
    env_id: "{{rancher_env.id}}"
    action: finish_upgrade
  when: upgrade_bc_stack.has_key("meta") and upgrade_bc_stack.meta.upgraded

- name: Upgrade healthcheck
  rancher_stack:
    rancher_parameters: "{{rancher_parameters}}"
    stack_name: healthcheck
    env_id: "{{rancher_env.id}}"
    docker_compose: "{{catalog_infra_dir}}/healthcheck/1/docker-compose.yml"
    rancher_compose: "{{catalog_infra_dir}}/healthcheck/1/rancher-compose.yml"
    external_id: "catalog://library:infra*healthcheck:1"
    action: upgrade
  register: upgrade_healthcheck_stack
  until: upgrade_healthcheck_stack.meta.upgraded
  retries: 5
  delay: 2

- name: Finish upgrade healthcheck
  rancher_stack:
    rancher_parameters: "{{rancher_parameters}}"
    stack_name: healthcheck
    env_id: "{{rancher_env.id}}"
    action: finish_upgrade
  when: upgrade_healthcheck_stack.meta.upgraded
  retries: 5
  delay: 2

- name: Upgrade scheduler
  rancher_stack:
    rancher_parameters: "{{rancher_parameters}}"
    stack_name: scheduler
    env_id: "{{rancher_env.id}}"
    docker_compose: "{{catalog_infra_dir}}/scheduler/2/docker-compose.yml"
    rancher_compose: "{{catalog_infra_dir}}/scheduler/2/rancher-compose.yml"
    external_id: "catalog://library:infra*scheduler:2"
    action: upgrade
  register: upgrade_scheduler_stack
  until: upgrade_scheduler_stack.meta.upgraded
  retries: 5
  delay: 2

- name: Finish upgrade scheduler
  rancher_stack:
    rancher_parameters: "{{rancher_parameters}}"
    stack_name: scheduler
    env_id: "{{rancher_env.id}}"
    action: finish_upgrade
  when: upgrade_scheduler_stack.meta.upgraded
  retries: 5
  delay: 2

- name: Deactive scheduler
  rancher_stack:
    rancher_parameters: "{{rancher_parameters}}"
    stack_name: scheduler
    env_id: "{{rancher_env.id}}"
    action: deactivateservices
  register: deactive_scheduler_stack
  until: deactive_scheduler_stack.meta.stopped
  retries: 5
  delay: 2

- name: Upgrade network services
  rancher_stack:
    rancher_parameters: "{{rancher_parameters}}"
    stack_name: network-services
    env_id: "{{rancher_env.id}}"
    docker_compose: "{{catalog_infra_dir}}/network-services/7/docker-compose.yml"
    rancher_compose: "{{catalog_infra_dir}}/network-services/7/rancher-compose.yml"
    external_id: "catalog://library:infra*network-services:7"
    action: upgrade
  register: upgrade_nw_stack
  until: upgrade_nw_stack.meta.upgraded
  retries: 5
  delay: 2

- name: Finish network services
  rancher_stack:
    rancher_parameters: "{{rancher_parameters}}"
    stack_name: network-services
    env_id: "{{rancher_env.id}}"
    action: finish_upgrade
  when: upgrade_nw_stack.meta.upgraded
  retries: 5
  delay: 2

- name: Active scheduler
  rancher_stack:
    rancher_parameters: "{{rancher_parameters}}"
    stack_name: scheduler
    env_id: "{{rancher_env.id}}"
    action: activateservices

