---
# Upgrade infra services
# version change:
#   ---------------------------------------
#   infra stack         |   old |   new   |
#   ---------------------------------------
#   beancounter-agent   |   1   |   2     |
#   healthcheck         |   0   |   1     |
#   network-services    |   6   |   7     |
#   scheduler           |   0   |   2     |
#   ---------------------------------------
# notice:
#   * before upgrading network-services, just make sure scheduler has been stopped.
#

- name: Upgrade infrastructure services
  hosts: 127.0.0.1
  connection: local
  vars:
    rancher_parameters:
      url: "http://54.222.227.190:8082"
      access_key: "8AB3F045EDCFA339B109"
      secret_key: "FkVfs5NBurvdP9TgSgdYwphmgFDxZ8EQBYnRKAEE"

  pre_tasks:
    - include: common-tasks/check_stack_state.yml
      ignore_errors: yes
      with_rancher_envs:
        - "{{rancher_parameters}}"
      loop_control:
        loop_var: rancher_env
        pause: 1
      vars:
        stacks:
          - beancounter-agent
          - healthcheck
          - network-services
          - scheduler
        should_health_state: healthy
        should_state: active
    - include: common-tasks/check_host_state.yml
      with_rancher_hosts:
        - "{{rancher_parameters}}"
      loop_control:
        loop_var: rancher_host
        pause: 1
      vars:
        should_agent_state: active

  tasks:
    - include: history-tasks/upgrade_infra_services_20170130.yml
      ignore_errors: yes
      with_rancher_envs:
        - "{{rancher_parameters}}"
      loop_control:
        pause: 1
        loop_var: rancher_env
      vars:
        catalog_infra_dir: "/Users/niusmallnan/rancher_work/rancher-catalog/infra-templates"
        influxdb_host: 172.31.2.230


