---
# Upgrade infra services
# It is a example.

- name: Upgrade infrastructure services
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - temp_rancher_config.yml

  pre_tasks:
    - include: common-tasks/check_stack_state.yml
      with_rancher_envs:
        - "{{rancher_parameters}}"
      loop_control:
        loop_var: rancher_env
        pause: 1
      vars:
        stacks:
          - healthcheck
          - network-services
          - scheduler
        should_health_state: healthy
        should_state: active
    - include: common-tasks/check_host_state.yml
      with_rancher_hosts:
        - "{{rancher_parameters}}"
      loop_control:
        loop_var: rancher_host
        pause: 1
      vars:
        should_agent_state: active

  tasks:
    - include: history-tasks/upgrade_infra_services_20170130.yml
      ignore_errors: yes
      with_rancher_envs:
        - "{{rancher_parameters}}"
      loop_control:
        pause: 1
        loop_var: rancher_env
      vars:
        catalog_infra_dir: "/Users/niusmallnan/rancher_work/rancher-catalog/infra-templates"


